### ISSUE TITLE
las descargas fallan hasta que se ingresa 'settings'

### ISSUE THREAD

**Issue by pyro12** [kodiar/kodiar.github.io#2]
He instalado esto en algunos sistemas y he notado que debes ingresar al 'settings' al menos una vez o las descargas fallarán.

**Comment by srprogrammer** [comment]
@pyro12  Creo que solucioné esto en la versión 0.4.3. Si tiene manera de probarlo te agradecería lo hicieras.

**Comment by pyro12** [comment]
Lo mejor que puedo hacer para probarlo ahora es desinstalarlo, eliminar todos los datos y reinstalarlo.

Lo hice y esta funcionando correctamente.
